name: Comprobar validez scripts p2
run-name: ${{ github.actor }} ha subido un script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Rama ${{ github.ref }}, repositorio ${{ github.repository }}."
    
      - name: Clonar repositorio al ejecutor
        uses: actions/checkout@v4
        
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pexpect
        # Agrega más paquetes si es necesario

      - name: Ejecutar script de comprobación
        run: |
          cd tests_practicas_AS/tests
          chmod u+x *
          ls -l
          bash test_practica2_todos.sh
#          bash tests_practicas_AS/tests/test_practica2_todos.sh

      - name: Comprobar finalizacion del trabajo
        run: echo "Estado del trabajo ${{ job.status }}."
